sudo: required
language: java
jdk:
 - openjdk12
services:
    - docker

before_install:
    - mvn clean install -Djasypt.encryptor.password=${JASYPT_PASS}
script:
    - docker build -t jdiaz/config-server  --build-arg ENC_PASS=$JASYPT_PASS .
